config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'login', to: 'sessions#login_form'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :comments, only: %i[create destroy]
  resources :values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  comment    :text             not null
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  value_id   :bigint
#
# Indexes
#
#  index_comments_on_value_id  (value_id)
#
# Foreign Keys
#
#  fk_rails_...  (value_id => "values".id)
#

class Comment < ApplicationRecord
  belongs_to :value
  validates :name, presence: true, length: {maximum: 10}
  validates :comment, presence: true, length: {maximum: 1000}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  admin           :boolean          default(FALSE), not null
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_secure_password
  has_many :values, dependent: :destroy
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
             format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 8 }
end

app/models/value.rb
# == Schema Information
#
# Table name: values
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_values_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Value < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    default_scope -> { order(created_at: :desc) }
    validates :title, presence:true, length: { maximum: 40 }
    validates :content, presence:true
    validates :user_id, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :current_user

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])  
  end
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to login_url
    end
  end
  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログイン済みです"
      redirect_to values_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = "コメントを保存しました。"
      redirect_to comment.value
    else
      flash[:comment] = comment
      flash[:error_messages] = comment.errors.full_messages
      redirect_back fallback_location: comment.value
    end 
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comment.value, flash: { notice: 'コメントが削除されました' }
  end

  def comment_params
    params.require(:comment).permit(:value_id, :name, :comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :forbid_login_user, only: :login_form

  def login_form
     
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to values_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'login_form'    
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to values_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_target_users, only: %i[show edit update destroy]
  before_action :authenticate_user, only: %i[index show edit update destroy]
  before_action :forbid_login_user, only: :new
  before_action :ensure_correct_user, only: %i[edit update]

  def new
    @user = User.new(flash[:user])
  end

  def edit
  end

  def show
    # @values = @user.values
    @value = Value.new(user_id: @user.id)
  end

  def index
    @users = User.all
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "ユーザー登録に成功しました"
      redirect_to user
    else
      redirect_to new_user_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def update
    if @user.update(user.params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to @user
    else

    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to users_path
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to values_url
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def set_target_users
      @user = User.find_by(id: params[:id])
    end
end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_target_value, only: %i[show edit update destroy]

  def new
    @value = Value.new(flash[:value])
  end

  def index
    @values = Value.page(params[:page])
  end

  def edit
    @value.attributes = flash[:value] if flash[:value]
  end

  def show
    @comment = Comment.new(value_id: @value.id)
  end

  def create
    value = current_user.values.build(value_params)
    if value.save
      flash[:notice] = "あなたの価値観を受付けました"
      redirect_to value
    else
      redirect_to new_value_path, flash: {
        value: value,
        error_messages: value.errors.full_messages
      }
    end
  end

  def update
    if @value.update(value_params)
      flash[:notice] = "編集が完了しました"
      redirect_to @value
    else
      redirect_to edit_value_path(@value), flash: {
        value: @value,
        error_messages: @value.errors.full_messages
      }
    end
  end

  def destroy
    @value.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to values_path
  end

  private 
    def value_params
      params.require(:value).permit(:title, :content)
    end

    def set_target_value
      @value = Value.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/comments/_comment.html.erb
<%= render 'shared/error_messages' %>

<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= comment.name %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
    <span><%= link_to '削除', comment, method: :delete, data: { confirm: '削除してもよろしいですか?' } %></span>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%= f.hidden_field :value_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/homes/top.html.erb
<h1>あなたの価値観をみんなと分かち合おう</h1>
<p>このサイトではみんなで価値観を共有してつながることができます。</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValueShareApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar  navbar-fixed-top navbar-inverse navbar-dark bg-dark">
      <div class="container">
        <nav>
          <ul class="nav navbar-navs">
            <% if @current_user %>
              <li><%= link_to "マイページ", @current_user %></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              <li><%= link_to "ユーザー一覧", users_path %></li>
              <li><%= link_to "新規投稿", new_value_path %></li>
            <% else %>
              <li><%= link_to "ログイン",  login_path %></li>
              <li><%= link_to "新規登録", new_user_path %></li>
            <% end %>
            <li><%= link_to "投稿一覧",   values_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/error_messages" %>

<%= form_with model: user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-controll' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-controll' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-controll' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード確認' %>
    <%= f.password_field :password_confirmation, class: 'form-controll' %>
  </div>
  <%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>

<%= render partial: 'form', locals: { user: @user } %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% if flash[:notice] %>
  <div class="alert alert-primary">
      <%= flash[:notice] %>
  </div>
<% end %>
<% @users.each do |user| %>
  <%= link_to user.name, user %>
<% end %>

app/views/users/new.html.erb
<h1>ユーザー新規作成</h1>

<%= render partial: 'form', locals: { user: @user } %>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>
<% if flash[:notice] %>
  <div class="alert alert-primary">
    <%= flash[:notice] %>
  </div>
<% end %>
<p><%= @user.name %></p>
<p><%= @user.email %></p>

<% if @current_user.id == @user.id %>
  <%= link_to "編集", edit_user_path(@current_user), class: "btn btn-primary" %>
  <%= link_to "退会", @value, method: :delete, data: { confirm: "本当に退会しますか?" }, class: "btn btn-primary" %>
<% end %>


 <div class="col-md-8">
    <% if @user.values.any? %>
      <h3>価値観一覧 (<%= @user.values.count %>)</h3>
      <ol class="microposts">
        <%= render @user.values %>
      </ol>
    <% end %>
  </div>

app/views/values/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: value do |f| %>
    <div class = "form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-controll' %>
    </div>
    <div class = "form-group" >
        <%= f.label :content, '価値観' %>
        <%= f.text_area :content, class: 'form-controll', rows: 10 %>
    </div>
    <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/values/_value.html.erb
<div class="p-comment__item">
  <div class="p-comment__bottomLine">
    <span class="user"><%= link_to value.user.name, value.user %></span>
    <span><%= value.title %></span>
    <span><%= value.created_at.to_s(:datetime_jp) %></span>
    <span><%= link_to '削除', value, method: :delete, data: { confirm: '削除してもよろしいですか?' } %></span>
  </div>
</div>

app/views/values/edit.html.erb
<h1>Values#edit</h1>
<p>Find me in app/views/values/edit.html.erb</p>

<%= render partial: 'form', locals: { value: @value } %>

app/views/values/index.html.erb
<h1>みんなの価値観一覧</h1>
<% if flash[:notice] %>
    <div class="alert alert-danger">
        <%= flash[:notice] %>
    </div>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>タイトル</th>
            <th>あなたの価値観</th>
        </tr>
    </thead>
    <tbody>
        <% @values.each do |value| %>
            <tr>
                <th><%= value.id %></th>
                <th><%= link_to value.title, value %></th>
                <th><%= simple_format(value.content) %></th>
            </tr>
        <% end %>
    </tbody>
    
</table>

<%= paginate @values %>

app/views/values/new.html.erb
<h1>あなたの価値観を共有してください</h1>

<%= render partial: 'form', locals: { value: @value } %>

app/views/values/show.html.erb
<% if flash[:notice] %>
    <div class="alert alert-primary">
        <%= flash[:notice] %>
    </div>
<% end %>
<h1><%= @value.title %></h1>
<p><%= simple_format(@value.content) %></p>

<%= link_to "編集", edit_value_path(@value) %>
<%= link_to "削除", @value, method: :delete, data: {confirm: "本当に削除しますか?"} %>
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <%= flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="p-comment__list">
    <div class="p-comment_title_listTitle">コメント</div>
    <%= render @value.comments %>
</div>

<%= render partial: 'comments/form', locals: { comment: @comment } %>